### PR TITLE
fix uid overflow on 32bit platforms

### PR DESCRIPTION
**Pull request by petrosagg**
Linux uses u32 as the {u,g}id map structures[1] but golang incorrectly uses ints[2]. Since changing the standard library is hard this commit only changes the parsing code to use the correct types and truncates the result to MaxInt.

The effect is that on 32bit platforms the namespaces will have at most 2 billion available uid instead of 4 billion.

[1] https://github.com/torvalds/linux/blob/v4.17/include/linux/user_namespace.h#L17-L21
[2] https://github.com/golang/go/blob/5c11480631f5654e9e6937ff08c453660138c64d/src/syscall/exec_linux.go#L14-L20

### CODE REVIEW

**Comment by vito** [comment]
Hmm, I'm a little afraid to merge this. This has to match closely to the values that Garden ([Guardian](https://github.com/cloudfoundry/guardian)) will use. Have you tried it out?

Checking on that, it looks like they use [a new `idmapper` package](https://github.com/cloudfoundry/idmapper/blob/master/max_valid_uid.go), which wasn't around when we hoisted this code out from Guardian. Maybe we could switch to that package and you could submit a PR there instead? That way we can make sure they're in sync.

**Comment by petrosagg** [comment]
This PR leaves the behaviour unchanged for 64bit builds, there shouldn't be any compatibility issues. 32bit builds were panicking so I don't think it can make it any worse :) That said, I didn't see any part that was depending on being able to express the full 32bit uint range and I've done some smoke tests by running it on a Pi. It worked fine and there are potentially a few more people that are testing it. See this thread https://github.com/concourse/concourse/issues/1379

I noticed that Guardian used idmapper which was basically the same code and I have a PR for that as well https://github.com/cloudfoundry/idmapper/pull/3 . Once it's merged I'll make a final PR to update the dependency version in Guardian.

In the meantime I think it's safe to merge this one that will unlock building concourse for arm

**Comment by vito** [comment]
@petrosagg OK, I'm happy to merge this too in the meantime.

Are you currently running on your fork of the `cloudfoundry/idmapper` package in addition to this change? I'm guessing that'd be panicking too if you weren't, so maybe we can just switch over to that package soon.

**Comment by petrosagg** [comment]
Yes I am. Switching to that package should be easy. As soon as it gets merged I'll resume the upstreaming

**Comment by vito** [comment]
Thanks! :+1:

**Pull request merged**
