### PR TITLE
concourse/#3819 adding zstd compression

### LINKED ISSUE #3819: Add alternate Compression algorithms
I've experimented with using zstd as a compression algorithm instead of gzip while streaming in and our with baggageclaim. From my totally scientific findings, its worth putting effort into. TLDR is its about 3x faster while maintaining the same compression ratio. For the test I compressed the Golang docker image rootfs. @cirocosta pointed out that we should be streaming inputs in parallel as this will help in scenarios like strabo, the only disadvantage to this was killing the worker by decompressing too much. This would not be a problem with Zstd or lz4. It was also pointed out that the rabbitMQ team would rather not have compression at all as they've seen it use too much CPU and since network is cheap, they wanted to experiment if it posed better results. This would be a good resolution for them as well.

Results:
**With ZSTD**
```
root@3bd4d72c2e4b:/tmp/test# time go run too_fast.go
&{/bin/tar [tar --exclude=./sys --exclude=./proc -C /dev/fd/3 -cf - .] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}

real	0m14.181s
user	0m9.600s
sys	0m3.750s

-rw-r--r--  1 root root 287M May  4 21:12 wholeworld.tar.zstd
```
`too_fast.go` is just `stream_in_out_linux.go` with a few modifications to use zstd.

**With GZIP**
```
root@3bd4d72c2e4b:/tmp/test# time tar --exclude=/sys --exclude=/proc --exclude=/tmp -czf wholebadworld.tar.gz /

real	0m45.507s
user	0m36.370s
sys	0m2.880s

-rw-r--r--  1 root root 297M May  4 21:16 wholebadworld.tar.gz
```

cc @ddadlani

### PR DESCRIPTION
**Pull request by kcmannem**
Fixes concourse/concourse/issues/3819

### CODE REVIEW

**Comment by kcmannem** [comment]
I think ztsd builds for windows, the tests (implying successful build) run on OSX and the zstd website has C# bindings so 🤞 hoping pipeline goes through.

**Comment by kcmannem** [comment]
Note: ATC requires streams out specific file (metadata file) from a volume so it must use the zstd decoding as well.

@vito 
Right now both compressions are available but are restricted for use in certain scenarios. Gzip for import_strategy and Zstd for StreamOut/In API calls. As to your comment in #3819 should we expose a parameter in StreamOut/In calls to choose compressions. That way we can still set the default to gzip as its a user friendly option. Or do you think we should go with inspecting the header to see which format to use.

**Comment by vito** [comment]
@kcmannem Protocol-wise, could we use the `*-Encoding` headers? So `Accept-Encoding` for `StreamOut` and `Content-Encoding` for `StreamIn`.

We'd still need to change the Go client methods to add a parameter. Would something like this make sense?:

```go
type Encoding string

const GzipEncoding Encoding = "gzip"
const ZstdEncoding Encoding = "zstd"

type Client interface {
  // ...

  // sets Content-Encoding
  StreamIn(path string, encoding Encoding, tarStream io.Reader) error

  // sets Accept-Encoding
  StreamOut(path string, encoding Encoding) (io.ReadCloser, error)

  // ...
}
```

**Comment by kcmannem** [comment]
@vito good idea, I'll look into it.

**Comment by cirocosta** [comment]
Using the headers sounds like a pretty cool idea - transitioning from workers that might not have the type compression that we want to support in future versions 👍

**Comment by kcmannem** [comment]
@vito finished up the changes, tested the streaming with 2 workers on docker compose. One thing to not is that clientVolume.StreamIn now needs an `Encoding` arg which will have to be propagated to `atc/worker/volume`.

Note: tests failed because go.mod wasn't updated to latest bc which is being pr'ed

**Review by ddadlani — DISMISSED** [review]
Could we squash some of these commits before we merge into master?

**Comment by kcmannem** [comment]
@vito tests have passed but something is wierd. I'm seeing this output in the ci but no ginkgo failures
```
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

••••••••
------------------------------

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
the other builds also had this print out so i dont think its specific to this branch.

Could you only approve this, I'll do a squash and merge.

**Pull request merged**
