### PR TITLE
Prevent nesting of volumes with `overlay` driver from exceeding kernel limit

### PR DESCRIPTION
**Pull request by vito**

### CODE REVIEW

**Comment by xtreme-sameer-vohra** [comment]
Based on the changes to Overlay recover, the workers would need to be recreated to ensure the recover method works

**Comment by xtreme-sameer-vohra** [comment]
Baggage claim unit test are failing
Screen Shot 2020-08-04 at 7 53 34 PM

**Comment by vito** [comment]
@xtreme-sameer-vohra They seem to be passing in CI? 🤔 That's the error you should see without the fix. How are you running the tests?

**Comment by xtreme-sameer-vohra** [comment]
> @xtreme-sameer-vohra They seem to be passing in CI? 🤔 That's the error you should see without the fix. How are you running the tests?

hmm interesting, I ran it on ci using
```
~/workspace/baggageclaim on fix-nested-volumes [?]
$ fly -t ci execute -p -c ci/unit-linux.yml -j baggageclaim/baggageclaim -i baggageclaim=.
```

and the error is from creating the first child volume. It looks like it didn't get far enough to try to created the doubly nested one.

**Review by xtreme-sameer-vohra — APPROVED** [review]
lgtm !

**Comment by vito** [comment]
@xtreme-sameer-vohra 👻 spooky 👻 

I re-ran the build a few times to be sure, and they passed. Would be nice to know why that happened, but I guess I'll merge anyway. 🤷‍♂️

**Pull request merged**
